### ISSUE TITLE
Search for stalonetrayrc under $XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by astier** [d3adb5/stalonetray#1]
Thank you for stalonetray. I have one feature-request. I would like to store my stalonetrayrc in `~/.config` which is defined by `$XDG_CONFIG_HOME`. It would be great if stalonetray would automatically search for stalonetrayrc under `$XDG_CONFIG_HOME/stalonetrayrc`.

**Comment by kolbusa** [comment]
Hi. Thanks for the report. Which one do you think should take precedence: `$HOME/.stalonetrayrc` or `$XDG_CONFIG_HOME/stalonetrayrc`?

**Comment by astier** [comment]
I think this would be a reasonable behavior.
